version: 2.1

jobs:
  build-and-package:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/repo
    steps:
      # 1) Clone (checkout) the repository
      - checkout

      # 2) Delete the test directories in each microservice
      - run:
          name: Delete test directories
          command: |
            echo "Deleting test directories..."
            for service in ApiGateway AuthService CartService InventoryService OrderService PaymentService ProductService ServiceRegistry; do
              rm -rf "$service/src/test"
              echo "Deleted test directory for $service"
            done
            echo "All test directories deleted."

      # 3) Clean & Package each microservice
      - run:
          name: Build (clean & package) each microservice
          command: |
            echo "Starting 'mvn clean package' for each microservice..."
            for service in ApiGateway AuthService CartService InventoryService OrderService PaymentService ProductService ServiceRegistry; do
              echo "-----------------------------------"
              echo "Building $service"
              cd "$service"
              mvn -B -DskipTests clean package
              cd ..
            done
            echo "All microservices have been packaged successfully."

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build-and-package
