version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: medium
    environment:
      JVM_OPTS: "-Xmx3200m"
      TERM: dumb

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Find pom.xml directory
          command: |
            POM_PATH=$(find . -name pom.xml | head -1)
            if [ -z "$POM_PATH" ]; then
              echo "No pom.xml found!"
              exit 1
            fi
            DIR_PATH=$(dirname "$POM_PATH")
            cd "$DIR_PATH"
      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - maven-dependencies-
      - run:
          name: Install Dependencies
          command: mvn dependency:resolve
      - save_cache:
          paths:
            - ~/.m2
          key: maven-dependencies-{{ checksum "pom.xml" }}

jobs:
  build-and-test:
    executor: java-executor
    steps:
      - setup
      - run:
          name: Build Application
          command: mvn clean package -DskipTests
      - run:
          name: Run Tests
          command: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/ecommerce-0.0.1-SNAPSHOT.jar
          destination: ecommerce.jar
workflows:
  version: 2
  build-test deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
                - develop
