# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/repo  # Set the working directory to the project root
    steps:
      - checkout
      - run:
          name: Build
          command: cd ApiGateway && mvn -B -DskipTests clean package
      - run:
          name: Test
          command: cd ApiGateway && mvn test

workflows:
  build-and-test:
    jobs:
      - build-and-test
