version: 2.1

jobs:
  build-and-package:
    docker:
      - image: cimg/openjdk:19.0.1
    working_directory: ~/repo
    # This tells CircleCI to run this job in parallel (4 containers in this example).
    parallelism: 4
    steps:
      # 1) Check out your code
      - checkout

      # 2) Delete test directories and build each microservice assigned to this container
      - run:
          name: Delete tests & Build Microservices in Parallel
          command: |
            # Define all microservices here
            SERVICES=(ApiGateway AuthService CartService InventoryService OrderService PaymentService ProductService ServiceRegistry)

            echo "Running on node index ${CIRCLE_NODE_INDEX} of ${CIRCLE_NODE_TOTAL}"
            for i in "${!SERVICES[@]}"; do
              # Use modulo arithmetic to distribute services across parallel containers
              if (( i % CIRCLE_NODE_TOTAL == CIRCLE_NODE_INDEX )); then
                service=${SERVICES[i]}
                echo "-----------------------------------"
                echo "Processing service: $service"
                # Remove test directories if needed
                rm -rf "$service/src/test"
                # Build & Package the service
                cd "$service"
                mvn -B -DskipTests clean package
                cd ..
              fi
            done

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build-and-package
