version: 2.1

jobs:
  build-and-test:
    docker:
    - image: cimg/openjdk:19.0.1
    working_directory: ~/repo # Set the working directory to the project root
    steps:
    - checkout
    - run:
        name: Delete Test Directories
        command: |
          echo "Deleting test directories..."
          rm -rf ApiGateway/src/test
          rm -rf AuthService/src/test
          rm -rf CartService/src/test
          rm -rf InventoryService/src/test
          rm -rf OrderService/src/test
          rm -rf PaymentService/src/test
          rm -rf ProductService/src/test
          rm -rf ServiceRegistry/src/test
          echo "Test directories deleted successfully."
    - run:
        name: Build ApiGateway
        command: cd ApiGateway && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd ApiGateway && mvn test
    - run:
        name: Build AuthService
        command: cd AuthService && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd AuthService && mvn test
    - run:
        name: Build CartService
        command: cd CartService && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd CartService && mvn test
    - run:
        name: Build InventoryService
        command: cd InventoryService && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd InventoryService && mvn test
    - run:
        name: Build OrderService
        command: cd OrderService && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd OrderService && mvn test
    - run:
        name: Build PaymentService
        command: cd PaymentService && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd PaymentService && mvn test
    - run:
        name: Build ProductService
        command: cd ProductService && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd ProductService && mvn test
    - run:
        name: Build ServiceRegistry
        command: cd ServiceRegistry && mvn -B -DskipTests clean package
    - run:
        name: Test
        command: cd ServiceRegistry && mvn test
  build:
    docker:
      - image: cimg/openjdk:17.0-node # Use a JDK image compatible with your project
     
    steps:
      - checkout
      - run:
          name: Check Java Version
          command: java -version
      - run:
          name: Install Sonar Scanner
          command: |
            curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
            unzip sonar-scanner.zip -d .
            mv sonar-scanner-4.7.0.2747-linux sonar-scanner
            export PATH=$PATH:$PWD/sonar-scanner/bin
      - run:
          name: Build Project
          command: cd ApiGateway && mvn clean install
      - run:
          name: Run SonarCloud Analysis
          command: |
            ./sonar-scanner/bin/sonar-scanner \
              -Dsonar.projectKey=$SONAR_PROJECT_KEY \
              -Dsonar.organization=$SONAR_ORGANIZATION \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN


workflows:
  build-and-test:
    jobs:
    - build-and-test
    - build:
        context: SonarCloud
