version: 2.1

executors:
  maven-executor:
    docker:
    - image: circleci/openjdk:17-jdk
    working_directory: ~/repo

jobs:
  build:
    executor: maven-executor
    steps:
    - checkout

    - run:
        name: Install Maven Dependencies
        command: mvn dependency:resolve

    - run:
        name: Run Tests
        command: mvn test

  package:
    executor: maven-executor
    steps:
    - checkout

    - run:
        name: Build Spring Boot Application
        command: mvn package -DskipTests

    - persist_to_workspace:
        root: .
        paths:
        - target

  deploy:
    executor: maven-executor
    steps:
    - attach_workspace:
        at: ~/repo

    - run:
        name: Deploy Application
        command: |
          echo "Deploying artifact to the staging environment..."
          # Add your deployment script or command here, such as uploading to a server or container registry.

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
    - package:
        requires:
        - build
    - deploy:
        requires:
        - package
