version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0  # Use an image with Java and Maven pre-installed
    working_directory: ~/repo
    steps:
      - checkout

      # Restore Maven cache (optional but recommended for faster builds)
      - restore_cache:
          keys:
            - maven-{{ checksum "pom.xml" }}
            - maven-

      - run:
          name: Compile All Microservices
          command: |
            for service in ApiGateway AuthService CartService InverntoryService OrderService PaymentService ProductService ServiceRegistry
            do
              echo "Compiling ${service} microservice..."
              cd ${service}
              mvn clean compile
              cd ..
            done

      # Save Maven cache (optional)
      - save_cache:
          paths:
            - ~/.m2
          key: maven-{{ checksum "pom.xml" }}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
