version: 2.1

executors:
  java-executor:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: "-Xmx3200m"

jobs:
  build-all-services:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: "Build and Test All Microservices"
          command: |
            mvn clean install -DskipTests=false
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build:
    jobs:
      - build-all-services
