name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    container:
      image: maven:3.8.5-openjdk-17

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: |
          chmod +x build-maven.sh
          ./build-maven.sh
      - name: artifacts make and update in artifact dir
        run: |
          chmod +x artifacts.sh
          ./artifacts.sh

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: artifacts/*.jar

  upload-to-jfrog:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:  
      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: target/

      - name: Install JFrog CLI
        run: |
          curl -fL https://install-cli.jfrog.io | sh
          echo "$HOME/.jfrog/bin" >> $GITHUB_PATH

      - name: Configure JFrog CLI
        run: |
          jf c add myplatform --url ${{ secrets.JFROG_URL }} --access-token ${{ secrets.JFROG_ACCESS_TOKEN }} --interactive=false
          jf c use myplatform

      - name: Upload JAR to JFrog
        run: jf rt upload "target/*.jar" linkinpark-libs-release/

  build-push-scan-docker:
    runs-on: ubuntu-latest
    needs: upload-to-jfrog
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifact
          path: target/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Search Dockerfiles and Build Images
        run: |
          BUILD_NUMBER=${{ github.run_number }}
          echo "Build Number: $BUILD_NUMBER"
          failures=0
          find . -name "Dockerfile" -exec sh -c '
            dir=$(dirname "{}")
            image_name="ashish233001/$(basename $dir):'"$BUILD_NUMBER"'"
            echo "Building Image: $image_name from directory: $dir"
            if docker build -t $image_name $dir; then
              echo "Pushing Image: $image_name"
              docker push $image_name
            else
              echo "Failed to build: $image_name"
              failures=$((failures+1))
            fi
          ' \;
          
          if [ $failures -gt 0 ]; then
            echo "$failures builds failed!"
            exit 1
          else
            echo "All Docker images built and pushed successfully!"
          fi

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}
          echo "Building image for $IMAGE_NAME"
          docker build -t $IMAGE_NAME --build-arg JAR_FILE=target/*.jar .
          docker push $IMAGE_NAME

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:${{ github.run_number }}
          severity: 'HIGH,CRITICAL'
          exit-code: 1
          ignore-unfixed: true
