name: Base CI Workflow

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  git-secrets-check:
    name: Git Secrets Check 🔑
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Git Secrets
        run: |
          sudo apt-get update
          sudo apt-get install git
          git clone https://github.com/ashish67876/ecommerce.git
          cd git-secrets && sudo make install
          git secrets --install
          git secrets --scan

  sonar-scan:
    name: SonarQube Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  
