name: ProductService CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'ProductService/**'
      - '.github/workflows/product-service-ci.yml'

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('ProductService/pom.xml') }}
          restore-keys: |
            maven-

      - name: Build with Maven
        run: |
          cd ProductService
          mvn clean package -DskipTests
